# Generated by Django 4.1 on 2022-08-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_status",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Status",
        ),
    ]
