# Generated by Django 4.1 on 2022-08-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_alter_contract_date_updated_alter_event_date_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
