# Generated by Django 4.1 on 2022-08-10 09:56

import EpicEvents.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("admin", "Admin"),
                            ("support", "Support"),
                            ("commercial", "Commercial"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", EpicEvents.authentication.models.UserManager()),
            ],
        ),
    ]
