# Generated by Django 4.1 on 2022-09-07 10:48

from django.db import migrations
from ..groups import create_groups


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_groups)]
