# Generated by Django 4.1 on 2022-08-18 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]
.
    operations = [(EpicEvents.authentication.groups.create_groups,)]
