# Generated by Django 4.1 on 2022-08-10 18:55

from django.db import migrations
from ..groups import create_groups


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_groups_user_user_permissions_and_more"),
    ]

    operations = [migrations.RunPython(create_groups)]
