# Generated by Django 4.1 on 2022-09-07 10:50

from django.db import migrations
from ..tests import create_test_users


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_auto_20220907_1248"),
    ]

    operations = [migrations.RunPython(create_test_users)]
