# Generated by Django 4.1 on 2022-09-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
