# Generated by Django 4.1 on 2022-09-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="date_updated",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="date_updated",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_updated",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
