# Generated by Django 4.1 on 2022-09-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_alter_client_date_created_alter_client_date_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="payment_due",
            field=models.DateTimeField(),
        ),
    ]
