# Generated by Django 4.1 on 2022-09-07 13:39

from django.db import migrations
from ..fake_users import create_test_users


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_auto_20220907_1539"),
    ]

    operations = [migrations.RunPython(create_test_users)]
